### PR TITLE
Generated app can be deployed

### LINKED ISSUE #47: Whippet deploy fails on new whippet generated apps
To replicate the issue:

```
mkdir -p ~/www/issue_test/shared/uploads
touch ~/www/issue_test/shared/wp-config.php
whippet generate app
cd ./whippet-app
whippet plugins install
whippet deploy ~/www/issue_test
```

Produces the error:

```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Checkout failed:

HEADPHP Warning:  file_get_contents(/home/user/www/issue_test//releases//../../shared/wp-config.php): failed to open stream: No such file or directory in /home/user/whippet/src/Modules/Deploy.php on line 78
```

It's caused by HEAD not pointing to anything (new repo) ...

The quick workaround for it is to just do an initial commit in the repo.
Is this something that would be worth adding in the 'generate' command?

### PR DESCRIPTION
**Pull request by snim2**
Whippet expects that a deployable app is a Git repo, with at least one commit. Previously, an app generated by Whippet was a Git repo, but did not have any commits, and so could not be deployed.

This commit adds a single commit to generated apps, to fix that.

Fixes #47

### Testing

Follow the instructions in the issue on `main` branch first:

```shell
mkdir -p ~/www/issue_test/shared/uploads
touch ~/www/issue_test/shared/wp-config.php
whippet generate app
cd ./whippet-app
whippet plugins install
whippet deploy ~/www/issue_test
```

You should see an error similar to the one reported:

```shell
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Checkout failed:
...
```

Run the same set of commands in this feature branch. Expected result is that the deploy continues, and fails much later because `wp-config.php` is empty.

----

- [ ] Includes tests (if new features are introduced)
- [x] Commit message includes link to the ticket/issue
- [x] Changelog updated
- [ ] PR open against [dxw's Homebrew Tap](https://github.com/dxw/homebrew-tap/) to point the Whippet formula to the new version number

### CODE REVIEW

File: generators/app/generate.php [hunk 1]
```diff
@@ -35,6 +36,12 @@ function generate() {
 
     $this->unzipAndRemoveTemplateZip();
 
+    // Whippet deploy requires at least one commit in the repo.
```
Comment (RobjS) [inline generators/app/generate.php:39]: Non-blocking suggestion: Would it be worth moving this slightly further down so that it happens after the permissions on the `script/` files have been fixed? 

This might also be a good time to remove the call to `$this->setWpVersion();`, as out default use case these days would be to pin to the major version set in the template repo.

**Review by RobjS — APPROVED** [review]
LGTM - just the one non-blocking suggestion.
